name: Link JIRA issue
on:
  pull_request_target:
    branches:
      - main
      - master
    types:
      - opened
jobs:
  jira-ticket-id-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            JIRA Ticket: [${{ github.event.pull_request.head.ref }}](https://commutatus.atlassian.net/browse/${{ github.event.pull_request.head.ref }})
          reactions: smile
