name: Create staging PR
on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
jobs:
  create-staging-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.event.pull_request.head.ref }}
          destination_branch: staging
          pr_title: "Staging PR"
          pr_body: ${{ github.event.pull_request.html_url }}
          github_token: ${{ secrets.TEST_PAT_GURPAL }}
